
	log.Printf("PACKAGE - FUNCTION : CALLED WITH ARGUMENTS\n")

	log.Printf("PACKAGE - FUNCTION : FAILED: ERROR=%v\n", err)

	log.Printf("PACKAGE - FUNCTION : SUCCESS: ARGUMENTS \n")

	log.Printf("PACKAGE - CALLING FUNCTION: ARGUMENTS \n")

	log.Printf("PACKAGE - PACKAGING TYPE: ARGUMENTS \n")

	log.Printf("PACKAGE - PACKAGED TYPE SUCCESS\n")
